---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        run: |
          docker-compose version
          docker version
      - name: Test
        run: ./test.sh
      - name: Check log
        run: docker-compose logs
        if: ${{ failure() }}
